---
language: python
python: "2.7_with_system_site_packages"

# Use the new container infrastructure
sudo: required

# Install ansible
addons:
  apt:
    packages:
    - python-pip
    - snmpd

install:
  # Install ansible
  # - pip install 
  #- pip install python-apt
  - pip install ansible
  # - pip install https://launchpad.net/ubuntu/+archive/primary/+files/python-apt_1.4.0~beta2.tar.xz

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-playbook --connection=local --sudo -v --diff tests/test.yml
  - >
    ansible-playbook --connection=local --sudo tests/test.yml
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)


notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
