---
# tasks file for observium-agent
- name: be sure xinetd is installed
  apt:  pkg=xinetd state=installed
  tags: xinetd
  when: ansible_distribution == "Debian"

- template: src=observium_agent_xinetd dest=/etc/xinetd.d/observium_agent_xinetd owner=root group=root mode=0644
  notify: restart xinetd
  tags:
  - xinetd

- name: enable xinetd
  service: name=xinetd state=started
  tags: xinetd

- name: deploy observium agent script
  template: src=observium_agent dest=/usr/bin/observium_agent owner=root group=root mode=0655

- name: deploy observium distro script
  template: src=distro dest=/usr/bin/distro owner=root group=root mode=0655

- lineinfile: dest=/etc/snmp/snmpd.conf line="#This line allows Observium to detect the host OS if the distro script is installed"
- lineinfile: dest=/etc/snmp/snmpd.conf line="extend .1.3.6.1.4.1.2021.7890.1 distro /usr/bin/distro"  
  notify: restart snmpd

- file: path=/usr/lib/observium_agent/local state=directory mode=0755

# TODO:  include only needed local agents via variables  
- template: src=local-agents/dpkg dest=/usr/lib/observium_agent/local/dpkg owner=root group=root mode=0655  

# apache local agent
- name: deploy apache local agent
  template: src=local-agents/apache dest=/usr/lib/observium_agent/local/apache owner=root group=root mode=0655  

- name: deploy apache mod_status configuration
  template: src=apache_status.conf dest=/etc/apache2/mods-enabled/status.conf owner=root group=root mode=0655  

# postgresql local agent
# TODO: separate task file
- name: install postgres python deps
  apt: pkg=python-psycopg2 state=installed

- name: deploy postgresql local agent
  template: src=local-agents/postgresql.conf dest=/usr/lib/observium_agent/local/postgresql.conf owner=root group=root mode=0600  

- template: src=local-agents/postgresql.pl dest=/usr/lib/observium_agent/local/postgresql.pl owner=root group=root mode=0655  

- name: Create a PostgreSQL database user
  postgresql_user: name={{ obs_agent_pg_user }} password={{ obs_agent_pg_pass }} role_attr_flags=CREATEDB state=present
  become: yes
  become_user: postgres
  become_method: sudo
  
- name: create db for observium user
  postgresql_db: name={{ obs_agent_pg_db }} owner={{ obs_agent_pg_user }}
  become: yes
  become_user: postgres
  become_method: sudo
  
