---

- name: "instal pre-reqs for postfix_mailgraph"
  package:
    name: "{{ item }}"
    state: present
  with_items:
   - mailgraph
   - rrdtool

# postfix_mailgraph local agent
- name: deploy postfix_mailgraph local agent
  template: src=local-agents/postfix_mailgraph dest=/usr/lib/observium_agent/local/postfix_mailgraph owner=root group=root mode=0655
